### ISSUE TITLE
Select helpers in verbs don't work with non-standard column names

### ISSUE THREAD

**Issue by martinzuba** [markfairbanks/tidytable#419] opened 2022-04-21 10:48 UTC
It seems to me that there is an undocumented requirement for column names to behave nice.

```
some_data <- crossing.(group = letters[1:10], 
                  year = 2000:2020) %>% 
  mutate.(.by = group,
          `value 1` = runif(n = 21) * 1:21 / 100 + 1,
          `value 2` = runif(n = 21) * 1:21 / 50 + 1)

annual_change <- some_data %>% 
  summarise.(.by = group, 
           across.(3:4,  function(x) { x/lag(x) }))
# works perfectly

annual_change <- some_data %>% 
  summarise.(.by = group, 
          .across(where(is.numeric), function(x) { x/lag(x) }))
# error
```

**Comment by markfairbanks** [comment] 2022-04-21 12:01
What error do you get? This works fine when I run it.

``` r
library(tidytable, warn.conflicts = FALSE)

some_data <- crossing.(group = letters[1:10], 
                  year = 2000:2020) %>% 
  mutate.(.by = group,
          `value 1` = runif(n = 21) * 1:21 / 100 + 1,
          `value 2` = runif(n = 21) * 1:21 / 50 + 1)

some_data %>% 
  summarise.(.by = group, 
             across.(where(is.numeric), function(x) { x/lags.(x)}))
#> # A tidytable: 210 × 4
#>    group  year `value 1` `value 2`
#>    <chr> <dbl>     <dbl>     <dbl>
#>  1 a     NA       NA        NA    
#>  2 a      1.00     1.02      1.01 
#>  3 a      1.00     0.992     0.999
#>  4 a      1.00     0.993     1.06 
#>  5 a      1.00     0.998     1.00 
#>  6 a      1.00     1.01      0.965
#>  7 a      1.00     1.02      1.00 
#>  8 a      1.00     1.03      1.01 
#>  9 a      1.00     0.975     0.967
#> 10 a      1.00     0.981     1.09 
#> # … with 200 more rows
```

**Comment by martinzuba** [comment] 2022-04-21 13:21
Hi. Thank for your reply. There was a typo in my example (`.across` instead of `across`.)

I am having somewhat of a difficulty since the error only exists with my data and not with the _identical_ test data.

Let me show you:


```
mydata.raw <- read_excel("some file.xlsx")

mydata <- mydata.raw %>% 
  select(Year = `...1`, Region = `...2`, `01 Personalkosten`, `02 Kosten für medizinische Gebrauchs- und Verbrauchsgüter`)  %>% 
  fill(Year, .direction = "down") %>% 
  # select small slice of original data
  filter(!is.na(`01 Personalkosten`), Year %in% paste(2016:2020), Region %in% c("1 Burgenland", "2 Kärnten", "3 Niederösterreich")) %>% 
  # change values to make reproducible
  mutate.(.by = Region,
             `01 Personalkosten` = 1:5,
             `02 Kosten für medizinische Gebrauchs- und Verbrauchsgüter` = 1:5 * 2)
  
testdata <- crossing(Year = paste(2016:2020),
                      Region = c("1 Burgenland", "2 Kärnten", "3 Niederösterreich")) %>% 
  mutate.(.by = Region,
          `01 Personalkosten` = 1:5,
          `02 Kosten für medizinische Gebrauchs- und Verbrauchsgüter` = 1:5 * 2)

all.equal(mydata, testdata) #TRUE
colnames(mydata) == colnames(testdata) #TRUE TRUE TRUE TRUE

testdata %>% 
  summarise.(.by = Region,
             across.(where(is.numeric), function(x) { x/lags.(x) })) # WORKS AS EXPECTED

mydata %>% 
  summarise.(.by = Region,
             across.(where(is.numeric), function(x) { x/lags.(x) }))
>
Error in `[.data.table`(~.df, , list(`01 Personalkosten` = (function(x) { : 
Supplied 5 items for column 1 of group 1 which has 15 rows. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.

mydata %>% 
  set_names(., names(.) %>% substr(1, 2)) %>% 
  summarise.(., .by = colnames(.)[2],
             across.(where(is.numeric), function(x) { x/lags.(x) })) # WORKS AS EXPECTED

mydata %>% 
  transmute.(Year, Region, `01 Personalkosten`, `05 long var whatevr uiaeui utirn uidta uaitdo -äuü` = `02 Kosten für medizinische Gebrauchs- und Verbrauchsgüter`) %>% 
  summarise.(., .by = colnames(.)[2],
             across.(where(is.numeric), function(x) { x/lags.(x) }))
# ALSO WORKS AS EXPECTED
```

It seems to me that loading the data via `read_excel` causes some issue with the colnames. The issue seems to be connected wtih something that even `all.equal()` does not check. Simply assignign new names will repair that.

Or it is gremlins.

**Comment by markfairbanks** [comment] 2022-04-21 15:56
Yeah unfortunately I'm not really sure what could be happening here 🤷‍♂️

Does it work when you use `mutate.()` instead of `summarize.()`? If you're doing `x/lags.(x)` you shouldn't need a summarize.

Does it work if you do something like `function(x) {mean(x)}?

I'm going to close this issue for now since I can't reproduce it, but we can keep discussing here.

**Closed by markfairbanks** 2022-04-21 15:56 UTC
