### ISSUE TITLE
transmute.() insists on name-value pairs unlike dplyr

### ISSUE THREAD

**Issue by torema-ed** [markfairbanks/tidytable#270] opened 2021-06-03 08:17 UTC
Hi, I encountered this small issue with `transmute.()` as I was changing my `dplyr` scripts to `tidytable`.

The reprex for it is below.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidytable)
#> 
#> Attaching package: 'tidytable'
#> The following object is masked from 'package:stats':
#> 
#>     dt
library(magrittr)

test_df = data.frame(
  a = 1:3,
  b = 4:6,
  c = 7:9
)

# dplyr works ok

test_df %>% transmute(a, b, c, d = a + b)
#>   a b c d
#> 1 1 4 7 5
#> 2 2 5 8 7
#> 3 3 6 9 9

# tidytable throws error

test_df %>% transmute.(a, b, c, d = a + b)
#> Error in mapply(.f, .x, .y, MoreArgs = list(...), SIMPLIFY = FALSE): zero-length inputs cannot be mixed with those of non-zero length

# but this works

test_df %>% transmute.(a = a, b = b, c = c, d = a + b)
#> # A tidytable: 3 x 4
#>       a     b     c     d
#>   <int> <int> <int> <int>
#> 1     1     4     7     5
#> 2     2     5     8     7
#> 3     3     6     9     9
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by moutikabdessabour** [comment] 2021-06-03 11:07
@markfairbanks adding the lines below at the top of `mutate.` solves the issue and mimics tidyverse behaviour:
```
  null_name_flag <- map_lgl.(names(dots), is_null)

  names(dots)[null_name_flag] <- sapply(dots[null_name_flag], ~ expr_name(get_expr(.x)))
```
the problem was caused by `NULL` dots names being passed to `map2.` in line 83.

**Comment by markfairbanks** [comment] 2021-06-03 14:49
@torema-ed Thanks for catching this

@moutikabdessabour This actually has a pretty easy fix available - `enquos()` has an auto-naming feature if you set `.named = TRUE`.

We would just have to set `dots <- enquos(..., .named = TRUE)` inside of `mutate`. Would you want to make a PR with this?

**Comment by markfairbanks** [comment] 2021-06-03 17:17
@moutikabdessabour Actually both of our solutions cause issues when `across.()` is used. I think the best option would be to use `exprs_auto_name()` after `prep_exprs()`

**Comment by moutikabdessabour** [comment] 2021-06-03 17:42
yeah I just noticed this when working on the other issue.

**Comment by markfairbanks** [comment] 2021-06-03 17:43
FYI I'm getting this one fixed now - I should have it closed in the next half hour or so

**Closed** 2021-06-03 18:01 UTC
Labels: bug

**Comment by markfairbanks** [comment] 2021-06-03 18:05
@torema-ed This is all fixed in the github version of tidytable. It should be on CRAN in 2-3 weeks.

``` r
library(tidytable)

test_df = data.frame(
  a = 1:3,
  b = 4:6,
  c = 7:9
)

test_df %>% transmute.(a, b, c, d = a + b)
#> # A tidytable: 3 × 4
#>       a     b     c     d
#>   <int> <int> <int> <int>
#> 1     1     4     7     5
#> 2     2     5     8     7
#> 3     3     6     9     9
```

**Comment by torema-ed** [comment] 2021-06-07 02:22
Wow, that's quick!

Thank you!!
